language: csharp
solution: XUnitTest.sln
install:
  - nuget restore XUnitTest.sln
  - nuget install xunit -Version 2.0.0
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release XUnitTest.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./XUnitTest/bin/Release/XUnitTest.dll