language: csharp
solution: XUnitTest.sln
install:
  - nuget restore XUnitTest.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release XUnitTest.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./XUnitTest/bin/Release/XUnitTest.dll